### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by odjhey** [odjhey/playground--godot-2d#1]
- [ ] add build scripts for multi targets (android, windows, mac, *nix)
- [ ] try adding sounds
- [ ] try adding more keebs shorts (for those with keebs)
- [ ] how to write tests? is there a godot way?
